name: Unit and Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
      - name: "Install Python"
        run: uv python install 3.13
      - name: "Install dependencies"
        run: uv sync
      - name: "Run tests"
        run: uv run pytest tests/ -v
